"""
The M9 cold-start demo: a topic never indexed before, taken end to end.

In:  a topic string (default: one from a field unrelated to both eval topics).
Out: examples/cold_start.md — the transcript, plus every tool call the agent made.
Runs against a scratch config pointing at data_demo/, so the eval corpus in data/ and
the M8 numbers measured against it are left untouched.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import time
from pathlib import Path
from typing import Any, Dict, List

import yaml

ROOT = Path(__file__).resolve().parents[1]

DEMO_ROOT = "data_demo"
DEFAULT_TOPIC = "protein structure prediction with deep learning"
# No explicit categories: the query planner picks its own and folds them into the query
# (arxiv_query.apply_categories, called at plan time). Passing more here would AND a
# second filter onto that one and narrow the search twice. Letting the planner choose is
# also the more honest demo — nothing is hand-tuned for this topic.

# Two questions: one the fresh corpus should answer, one it cannot. The second is the
# point of the demo as much as the first — a system that answers everything has not
# demonstrated abstention.
ANSWERABLE = "What model architectures do these papers use to predict protein structure, and what do they report about accuracy?"
UNANSWERABLE = "What do these papers say about sourdough fermentation temperature and starter culture biology?"


def scratch_config(fresh: bool) -> Path:
    """A config identical to the project's but rooted at data_demo/.

    Written through the YAML rather than poked into a loaded Config: config sections are
    read-only by design, and the demo should exercise the same load path the CLI uses.
    """
    raw = yaml.safe_load((ROOT / "config.yaml").read_text(encoding="utf-8"))
    # arXiv answers 429 and 503 intermittently under load, and one failed search costs
    # the whole demo (~20 minutes of downloads, vision calls and two agent runs). A
    # slightly wider retry budget and a wider gap than the project default is about
    # surviving a flaky feed without leaning on it: retries are few, and the client
    # leaves 6s between requests rather than the 4s used for ordinary indexing.
    raw["collection"]["max_retries"] = 4
    raw["collection"]["request_delay_s"] = 6
    raw["paths"] = {
        "data_dir": DEMO_ROOT,
        "papers_dir": f"{DEMO_ROOT}/papers",
        "index_dir": f"{DEMO_ROOT}/index",
        "cache_dir": f"{DEMO_ROOT}/cache",
        "logs_dir": f"{DEMO_ROOT}/logs",
        "prompts_dir": "src/prompts",
    }
    demo_dir = ROOT / DEMO_ROOT
    if fresh and demo_dir.exists():
        shutil.rmtree(demo_dir)
    demo_dir.mkdir(parents=True, exist_ok=True)
    path = demo_dir / "config.yaml"
    path.write_text(yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")
    return path


def assert_cold(config) -> None:
    """A demo that starts with papers already indexed is not a cold start."""
    chunks = config.paths.chunks
    if chunks.exists() and chunks.stat().st_size > 0:
        raise SystemExit(
            f"{chunks} is not empty — this would not be a cold start. Re-run with --fresh."
        )


def render(topic: str, indexing: Dict[str, Any], runs: List[Dict[str, Any]]) -> str:
    """The transcript, as markdown."""
    lines = [
        "# Cold-start demo",
        "",
        f"A topic the system had never seen, taken from nothing to an answered question. "
        f"Generated by `scripts/m9_cold_start.py`; corpus in `{DEMO_ROOT}/`, separate from "
        "the eval corpus in `data/`.",
        "",
        f"**Topic:** `{topic}`  ",
        f"**Date:** {time.strftime('%Y-%m-%d')}  ",
        f"**Starting state:** no papers, no chunks, no index",
        "",
        "## 1. Indexing",
        "",
        "```",
        f"$ python main.py --config {DEMO_ROOT}/config.yaml index \"{topic}\"",
        indexing["stdout"].rstrip(),
        "```",
        "",
        f"arXiv query the planner produced: `{indexing.get('arxiv_query', 'n/a')}`",
        "",
        f"Papers: {indexing['papers']} · chunks: {indexing['chunks']} · "
        f"figures: {indexing['figures']} · vectors: {indexing['vectors']} · "
        f"wall clock: {indexing['elapsed_s']:.0f}s",
        "",
    ]
    for n, run in enumerate(runs, start=2):
        lines += [
            f"## {n}. {run['label']}",
            "",
            "```",
            f"$ python main.py --config {DEMO_ROOT}/config.yaml ask \"{run['question']}\"",
            "```",
            "",
            "**Tool calls**",
            "",
            "```",
        ]
        for record in run["trace"]:
            returned = record.get("error") or f"{len(record.get('chunk_ids_returned') or [])} chunk(s)"
            args = json.dumps(record.get("args"))
            lines.append(
                f"[{record['iteration']}] {record['tool_name']}({args[:110]}) "
                f"-> {returned}, {record['latency_ms']}ms"
            )
        lines += [
            "```",
            "",
            "**Answer**",
            "",
            run["answer"].strip(),
            "",
            f"*{run['iterations']} iteration(s), {run['tool_calls']} tool call(s), "
            f"{run['context_tokens']} context tokens, stopped: {run['stopped_because']}, "
            f"{run['elapsed_s']:.0f}s*",
            "",
        ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the M9 cold-start demo.")
    parser.add_argument("--topic", default=DEFAULT_TOPIC)
    parser.add_argument("--max-results", type=int, default=3,
                        help="papers to fetch; kept small because every figure costs a vision call")
    parser.add_argument("--fresh", action="store_true", help=f"delete {DEMO_ROOT}/ first")
    parser.add_argument("--out", default="examples/cold_start.md")
    args = parser.parse_args()

    config_path = scratch_config(args.fresh)
    os.environ["SCIAGENT_CONFIG"] = str(config_path)
    sys.path.insert(0, str(ROOT / "src"))
    sys.path.insert(0, str(ROOT))

    from config import CFG
    from agent.loop import AgentLoop
    from agent.tool_registry import build_full_registry
    from corpus.collect import search_and_fetch
    from extraction.ingest import ingest_all
    from retrieval.embedder import Embedder
    from retrieval.indexer import index_chunks
    from tools.retrieve_evidence import EvidenceRetriever

    CFG.paths.ensure()
    assert_cold(CFG)
    print(f"cold start in {CFG.paths.data}", flush=True)

    started = time.perf_counter()
    stdout: List[str] = []

    def say(line: str) -> None:
        print(line, flush=True)
        stdout.append(line)

    say(f"[1/3] searching arXiv for {args.topic!r} ...")
    collected = search_and_fetch(args.topic, max_results=args.max_results, config=CFG)
    if "error" in collected:
        raise SystemExit(f"collection failed: {collected}")
    say(f"      {len(collected['papers_added'])} added, "
        f"{collected['papers_skipped']} already held, tag {collected['topic_tag']!r}")

    say("[2/3] extracting text and figures ...")
    ingested = ingest_all(config=CFG, describe=True)
    say(f"      {ingested['chunks_total']} chunks, {ingested['figures_total']} figures")

    say("[3/3] embedding and indexing ...")
    indexed = index_chunks(config=CFG)
    if "error" in indexed:
        raise SystemExit(f"indexing failed: {indexed}")
    say(f"      {indexed['chunks_indexed']} embedded, {indexed['cache_hits']} cache hit(s), "
        f"{indexed['total_indexed']} vectors in the index")

    indexing = {
        "stdout": "\n".join(stdout),
        "papers": len(collected["papers_added"]),
        "chunks": ingested["chunks_total"],
        "figures": ingested["figures_total"],
        "vectors": indexed["total_indexed"],
        "arxiv_query": collected.get("arxiv_query"),
        "elapsed_s": time.perf_counter() - started,
    }

    retriever = EvidenceRetriever(CFG, embedder=Embedder(CFG))
    loop = AgentLoop(build_full_registry(retriever=retriever, config=CFG),
                     config=CFG, retriever=retriever)

    runs = []
    for label, question in (
        ("A question the fresh corpus can answer", ANSWERABLE),
        ("A question it cannot — the abstention case", UNANSWERABLE),
    ):
        print(f"\n--- {label}\n{question}", flush=True)
        began = time.perf_counter()
        result = loop.run(question)
        if "error" in result:
            raise SystemExit(f"agent loop failed: {result['error']} — {result['detail']}")
        print(result["answer"], flush=True)
        runs.append({
            "label": label,
            "question": question,
            "answer": result["answer"],
            "trace": result["trace_records"],
            "iterations": result["iterations"],
            "tool_calls": result["tool_calls"],
            "context_tokens": result["context_tokens"],
            "stopped_because": result["stopped_because"],
            "elapsed_s": time.perf_counter() - began,
        })

    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(args.topic, indexing, runs), encoding="utf-8")
    print(f"\ntranscript written to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
