"""
Renders examples/worked_examples.md from the saved M8 eval results.

In:  eval/results/{tuning_split,held_out_split}.json and eval/questions.json.
Out: a markdown file of real, already-scored runs — an abstention, a conflicting-evidence
     case, and a straightforward one. Generated rather than transcribed so the answers
     and metrics cannot drift apart from the JSON that scored them.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]

# (question_id, heading, why this example is here)
PICKS = [
    ("ni01", "Abstention — a question the corpus cannot answer",
     "The corpus holds machine-learning papers. This question is about sourdough. An "
     "honest \"I don't have evidence for this\" is the correct answer, and a "
     "plausible-sounding one built on weak retrieval would be a failure even if it "
     "happened to be true."),
    ("cf01", "Conflicting evidence — the sources disagree",
     "The agent is required to surface a disagreement rather than pick the more "
     "convincing side or average it away. Note that it also explains *why* the sources "
     "differ, which is the part that makes the conflict useful rather than confusing."),
    ("mp01", "Multi-paper synthesis — the ordinary case",
     "Included for contrast: what a normal, well-evidenced answer looks like."),
]


def load() -> Dict[str, Dict[str, Any]]:
    questions = {q["question_id"]: q
                 for q in json.loads((ROOT / "eval/questions.json").read_text())["questions"]}
    rows: Dict[str, Dict[str, Any]] = {}
    for split in ("tuning_split", "held_out_split"):
        path = ROOT / "eval/results" / f"{split}.json"
        if not path.exists():
            continue
        for row in json.loads(path.read_text())["rows"]:
            rows[row["question_id"]] = {**row, "split": split}
    return {qid: {**questions[qid], **rows[qid]} for qid in rows if qid in questions}


def render(records: Dict[str, Dict[str, Any]]) -> str:
    lines = [
        "# Worked examples",
        "",
        "Real runs against the 11-paper eval corpus, lifted from the scored M8 results in "
        "`eval/results/` — not re-run for this document, so every answer here is one the "
        "eval harness actually graded. Generated by `scripts/m9_examples.py`.",
        "",
        "See `docs/EVALUATION.md` for the corpus these ran against and the full metrics. "
        "For a topic taken from nothing to an answered question, see "
        "`examples/cold_start.md`.",
        "",
    ]
    for n, (qid, heading, why) in enumerate(PICKS, start=1):
        record = records.get(qid)
        if record is None:
            continue
        lines += [
            f"## {n}. {heading}",
            "",
            f"> **{record['question']}**",
            "",
            f"*{why}*",
            "",
            f"`{qid}` · category `{record['category']}` · {record['split'].replace('_', ' ')}",
            "",
            "**Tools the agent chose**",
            "",
            "```",
            f"used:     {' -> '.join(record['tools']['used']) or '(none)'}",
            f"expected: {', '.join(record['tools']['expected']) or '(none)'}",
        ]
        if record["tools"].get("missing"):
            lines.append(f"missing:  {', '.join(record['tools']['missing'])}")
        if record["tools"].get("unexpected"):
            lines.append(f"extra:    {', '.join(record['tools']['unexpected'])}")
        citations = record["citations"]
        coverage = record["fact_coverage"]
        coverage_text = "n/a (abstention)" if not isinstance(coverage, (int, float)) or coverage != coverage else f"{coverage:.2f}"
        lines += [
            "```",
            "",
            "**Answer**",
            "",
            record["answer"].strip(),
            "",
            f"*{record['iterations']} iteration(s), {record['tool_calls']} tool call(s), "
            f"{record['elapsed_ms'] / 1000:.0f}s · fact coverage {coverage_text} · "
            f"citations {citations['resolved']}/{citations['total']} resolved · "
            f"abstained: {str(record['abstained']).lower()} "
            f"(expected: {str(record['expect_abstention']).lower()})*",
            "",
        ]
    return "\n".join(lines)


if __name__ == "__main__":
    out = ROOT / "examples/worked_examples.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(load()), encoding="utf-8")
    print(f"written to {out}")
